"""remove workspace_id from workflows

Revision ID: 488846b86e90
Revises: 73b7bec44615
Create Date: 2025-12-18 16:47:16.267554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488846b86e90'
down_revision: Union[str, None] = '73b7bec44615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workflows_workspace_id_fkey'), 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('workflows_workspace_id_fkey'), 'workflows', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###
